language: cpp

compiler:
  - clang

before_script:
  - pwd
  - echo $HOME
  - PATH=$PATH:/home/travis/build/DanoPrat/Netanomy/lib
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/travis/DanoPrat/Netanomy
  - mkdir lib
  - cd lib
  - wget http://download.zeromq.org/zeromq-4.0.1.tar.gz
  - tar xzf zeromq-4.0.1.tar.gz
  - cd zeromq-4.0.1
  - ./configure --prefix=/home/travis/build/DanoPrat/Netanomy/lib
  - make
  - make install
#  - sudo apt-get install libzmq-dev
  - sudo ldconfig -v | grep -i libzmq
  - cd ..
  - cd ..
  - mkdir build
  - cd build
  - pwd
  - ls $HOME/build/DanoPrat/Netanomy
  - ls $HOME/build/DanoPrat/Netanomy/lib
  - ls $HOME/build/DanoPrat/Netanomy/lib/zeromq-4.0.1
  - ls -l $HOME/build/DanoPrat/Netanomy/lib/include
  - ls -l $HOME/build/DanoPrat/Netanomy/lib/lib
  - cmake -DZMQ_INCLUDE=$HOME/build/DanoPrat/Netanomy/lib/include -DZMQ_LIBRARY=$HOME/build/DanoPrat/Netanomy/lib/lib/libzmq.so ..

script: make
