language: cpp

compiler:
  - clang

before_script:
  - mkdir lib
  - cd lib
  - wget http://download.zeromq.org/zeromq-4.0.1.tar.gz
  - tar xzf zeromq-4.0.1.tar.gz
  - cd zeromq-4.0.1
  - ./configure --prefix=/home/travis/build/DanoPrat/Netanomy/lib
  - make
  - sudo make install
  - ldconfig -v | grep -i libzmq
  - cd ..
  - cd ..
  - mkdir build
  - cd build
  - cmake -DZMQ_INCLUDE_DIR=/home/travis/build/DanoPrat/Netanomy/lib/include -DZMQ_LIBS=/home/travis/build/DanoPrat/Netanomy/lib/lib ..

script: make
