language: cpp

compiler:
  - clang

before_script:
  - PATH=$PATH:/home/travis/build/DanoPrat/Netanomy/lib
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/travis/build/DanoPrat/Netanomy
  - mkdir lib
  - cd lib
  - wget http://download.zeromq.org/zeromq-4.0.1.tar.gz
  - tar xzf zeromq-4.0.1.tar.gz
  - cd zeromq-4.0.1
  - ./configure --prefix=/home/travis/build/DanoPrat/Netanomy/lib
  - make
  - make install
#  - sudo apt-get install libzmq-dev
  - sudo ldconfig -v | grep -i libzmq
  - cd ..
  - cd ..
  - mkdir build
  - cd build
  - cmake cmake -DZMQ_INCLUDE=$HOME/Netanomy/lib/zeromq-4.0.1/include -DZMQ_LIBRARY=$HOME/Netanomy/lib/zeromq-4.0.1/lib/libzmq.so..

script: make
